language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install gnome gdm
    - sudo apt-get update -qq
    - sudo apt-get install -yqq 
    - sudo apt-get install python-nose
    - sudo apt-get install python-notify
script: nosetests tests --verbose
